BUT THE STAIR CASE SEARCH IS THE MOST OPTIMIZED SOLUTION FOR THIS PROBLEM SO NEVER USE THE BRUTEFORCE AND BINARY SEACH
//  TECHNIQUE TO SOLVE THIS PROBLEM THAT IS FOR YOUR BETTER UNDERSTAND ONLY SO NEVER NEVER 
//  USE THOSE 2 IN ANY INTERVIEW OR CODING TEST OR IN ANY CODING PLATFORM BECAUSE MOST OF 
//  THE CODING PLATFORM TAKE ONLY OPTIMIZED CODE